### ISSUE TITLE
DeprecationWarning The 'warn' method

### ISSUE THREAD

**Issue by KKomarov** [launchdarkly/python-server-sdk#125]
6.9.1 version, I got deprecation warning about `warn`. Can you fix these annoying messages?
```
C:\Python37\lib\site-packages\ldclient\client.py:287: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    + str(default) + " for feature key: " + key)
```

**Comment by eli-darkly** [comment]
Looks like `warn` and `warning` work identically in 2.7 (our lowest compatible version) but `warn` started causing a deprecation warning in some later Python version. Should be an easy fix - thanks for catching this.

**Comment by eli-darkly** [comment]
OK, the 6.9.3 release includes a fix for this. Thanks again.

**Comment by eli-darkly** [comment]
Note that if you were previously using 6.9.1, the package name has changed. You will need to change `ldclient-py` to `launchdarkly-server-sdk` in your requirements, and uninstall any copies of `ldclient-py` that you currently have.

**Comment by KKomarov** [comment]
@eli-darkly Thank you for the notification
