### ISSUE TITLE
Unexpected keyword argument 'total' prevents events from being sent

### ISSUE THREAD

**Issue by mrdon** [launchdarkly/python-server-sdk#143]
Occasionally, I see this in the logs:

Unhandled exception in event processor. Analytics events were not processed. [__init__() got an unexpected keyword argument 'total']

It doesn't happen all the time, and I think I traced it down to how retries are handled.  This library uses a _EventRetry subclass of urllib3.Retry, however, Retry will try to recreate itself via the "new" function, passing in all the arguments it received.  Unfortunately, _EventRetry doesn't support any of those arguments, specifically 'total', and I think this is causing the error.

The fix would be to, at a minimum, add **kwargs to the constructor, or better yet, pass those same arguments down.

**Comment by eli-darkly** [comment]
Thanks for catching this. I'm not even sure why we're bothering to use the urllib3 retry functionality at all, rather than just doing the retry ourselves, especially since there are some cases where we really should not bother retrying (like if we get a 401). I'm also not sure why we've never seen this problem before, unless we simply didn't test retrying of failed posts at all in our unit tests (I know we do in the other SDKs, but the Python code has probably been updated a bit less than the rest).

**Comment by mrdon** [comment]
To be honest, I still haven't figured out how to reproduce it locally - I even hacked event_processor to trigger a retry via changing the uri to one that always returns 502s, but it doesn't trigger that Retry.new code path.

**Comment by jason-kane** [comment]
+1, I'm seeing Unhandled exception in event processor. Analytics events were not processed. [__init__() got an unexpected keyword argument 'total']

**Comment by eli-darkly** [comment]
There's a patch for this in progress - sorry it hasn't been released yet.

**Comment by eli-darkly** [comment]
This release was blocked for tedious process reasons but is now available.

**Comment by mrdon** [comment]
I'm not sure this was fixed.  I upgraded to 6.13.1 today but am still seeing the error:
Unhandled exception in event processor. Analytics events were not processed. [__init__() got an unexpected keyword argument 'total']

**Comment by eli-darkly** [comment]
@mrdon That's very odd and I don't see how it is possible. The logic that used `urllib.Retry` was removed, and there are no longer any uses of any keyword called "total" anywhere in the SDK code. I know this is an annoying question but... are you _sure_ you're using 6.13.1? I just checked the PyPI download to make sure that what we released really did include that change, and it looks fine to me.

**Comment by mrdon** [comment]
Yep, sorry, Pipenv didn't generate the right lock file. :disappear:

**Comment by eli-darkly** [comment]
Whew
