### ISSUE TITLE
Unexpected keyword argument 'connect_timeout'

### ISSUE THREAD

**Issue by rrhodes** [launchdarkly/python-server-sdk#149]
Latest version of the LaunchDarkly client (v7.0.0 at the time of writing) doesn't support the 'connect_timeout' configuration argument in my code. This is running Python 3.9 on Mac OS Catalina.

Example code:

```python
import ldclient
from ldclient.config import Config

def main():
    ldclient.set_config(Config(sdk_key='test-key', connect_timeout=5))

if __name__ == "__main__":
    main()
```

Response from the code:

```bash
TypeError: __init__() got an unexpected keyword argument 'connect_timeout'
```

**Expected behavior**
A LaunchDarkly client to be instantiated for use in my code.

**Comment by hroederld** [comment]
Hello @rrhodes 

We follow semantic versioning and `7.0.0` is a new major version. Quoting the changelog:

- Removed the individual HTTP-related parameters such as `connect_timeout` from the [`Config`](https://launchdarkly-python-sdk.readthedocs.io/en/latest/api-main.html#ldclient.config.Config) type. The correct way to set these now is with the [`HTTPConfig`](https://launchdarkly-python-sdk.readthedocs.io/en/latest/api-main.html#ldclient.config.HTTPConfig) sub-configuration object: `Config(sdk_key = "my-sdk-key", http = HTTPConfig(connect_timeout = 10))`.

**Comment by eli-darkly** [comment]
To We strongly advise reading this changelog whenever updating to a new version, _especially a new major version_ since any major version update is by definition not entirely backward-compatible without code changes.

The `connect_timeout` parameter is now in a separate configuration object for HTTP configuration. That has been the case since

**Comment by rrhodes** [comment]
Thanks for sharing this. [Can the documentation be updated](ldclient.set_config(Config(sdk_key='YOUR_SDK_KEY', connect_timeout=5))
) to reflect this change please?

**Comment by hroederld** [comment]
Ah I see the confusion. The doc.launchdarkly.com info is definitely outdated. I'll file a ticket. Thanks!
