### ISSUE TITLE
Getting numerous Error posting diagnostic event (giving up permanently): HTTP error 401 (invalid SDK key)

### ISSUE THREAD

**Issue by MVran** [launchdarkly/python-server-sdk#180]
After init code part

 if self.client.get().is_initialized():
            logger.info("Launch Darkly SDK successfully initialized.")
I get "Launch Darkly SDK successfully initialized."
I've double checked sdk key and it's right as well as reading flags.
Confg is simple containing only sdk key.
self.client.set_config(Config(sdk_key))
Logs
I have started getting
Error posting diagnostic event (giving up permanently): HTTP error 401 (invalid SDK key)
Deployment is on kubernetes with multiple pods, and framework is Flask, it some race condition happening here?
Note that in local I am not getting this message.

SDK version
launchdarkly-server-sdk = "^7.4.2"

Language version, developer tools
python 3.9

OS/platform
For instance, Ubuntu 16.04

**Comment by eli-darkly** [comment]
Hi, thanks for reporting this. I've been trying to think how it could happen, but so far it's still mysterious to me and I don't think we've ever seen such an issue before. The SDK uses the same SDK key for authorization in every HTTP request that it makes— there's nothing special about these event posts in that regard. Do I understand correctly that the "Error posting diagnostic event" lines are the _only_ errors you're seeing in the log; it isn't complaining about any other kinds of requests failing?

**Comment by eli-darkly** [comment]
Also, are you seeing analytics data on your dashboard (assuming you use that feature)?

**Comment by MVran** [comment]
Hi Eli, thanks for looking into this. I've found that the bug was due to oor deployment, where one monolith was split accross pods, but not all of them contained ld sdk.

**Comment by eli-darkly** [comment]
@MVran Aha! Glad to know it's resolved.
