### ISSUE TITLE
Please release a wheel to pypi

### ISSUE THREAD

**Issue by gilbahat** [launchdarkly/python-server-sdk#183]
Hi,

We really want to have a wheel for this package. As we are currently migrating to arm64, the lack of a prebuilt wheel will cause the wheel build process to run under emulation, even though it is completely redundant, adding quite a few more seconds to the build time unnecessarily.

adding a bdist_wheel to your CI release should take a few minutes at most.

**Comment by keelerm84** [comment]
Thank you for filing this request and providing some insight into your use case. I will try to take a look at adding this sometime over the next week.

Filed internally as `sc-168549`
