### ISSUE TITLE
Can we loosen the semver requirement to include version 3.0?

### ISSUE THREAD

**Issue by bkodes** [launchdarkly/python-server-sdk#214]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would love to see the SDK [...does something new...]
Hey I am utilizing ld python sdk but i have conflicting semver versions with lancedb. Is there any chance we can loosen the requirement on semver here to include =<3.0 instead of <3.0?

**Describe the solution you'd like**
Can we evaluate what is needed to include semver 3.0? Version vs VersionInfo is my biggest conflict right now with your packages

**Describe alternatives you've considered**
I will do whatever work needs to be done if we are okay with this

**Additional context**
Add any other context about the feature request here.

**Comment by keelerm84** [comment]
This SDK does not have a requirement on `lancedb`. It seems like this is more likely a problem with transitive dependencies. If you can make a small reproduction case, and send me the `requirements.txt` file, I can see if there is something we can do on our side.

**Comment by pierre-wehbe** [comment]
@keelerm84 Can we please re-open this.

**File**: https://github.com/launchdarkly/python-server-sdk/blob/main/requirements.txt
**Current dependency**: semver>=2.10.2,<3.0.0
**Need**: semver 3.0.1 (latest version here: https://pypi.org/project/semver/)

Can we loosen the semver requirement to include version 3.0?
