### ISSUE TITLE
Can we loosen the semver requirement to include version 3.x

### ISSUE THREAD

**Issue by pierre-wehbe** [launchdarkly/python-server-sdk#215]
@keelerm84

File: https://github.com/launchdarkly/python-server-sdk/blob/main/requirements.txt
Current dependency: semver>=2.10.2,<3.0.0
Need: semver 3.0.1 (latest version here: https://pypi.org/project/semver/)

Can we loosen the semver requirement to include version 3.0?
Some python sdk's we're using require semver>=3.xx

**Comment by keelerm84** [comment]
Released in 8.1.5
