### ISSUE TITLE
urllib3 < 1.26 not supported

### ISSUE THREAD

**Issue by claudio-cantalupo-ca** [launchdarkly/python-server-sdk#270]
**Is this a support request?**
No

**Describe the bug**
The minimum requirement specified in pyproject.toml for urllib3 is not correct: `urllib3 = ">=1.22.0"` it should be `urllib3 = ">=1.26.0"` 

Tried with urllib3 = 1.25.11 and the client initialization continuosly logs this warning:
`Unexpected error on stream connection: __init__() got an unexpected keyword argument 'other', will retry`

This should be an error by the way because the client will never be able to connect, it just infinitely pollutes the logs.

**To reproduce**
Put these lines in a requirements.txt and install them in a new venv:
```
launchdarkly-server-sdk==9.2.0
urllib3==1.25.11
```
Just init a new client as explained in the LD official doc.

**SDK version**
v9.2.0 (python 3.9.18)

**Comment by keelerm84** [comment]
Thank you for reporting this issue! I will let you know once we have a fix released for the SDK as well as the event source.

**Comment by keelerm84** [comment]
Fixed in v9.2.1.

**Comment by claudio-cantalupo-ca** [comment]
Thanks for the quick fix!

Regards.
