### ISSUE TITLE
Warning flooding logs

### ISSUE THREAD

**Issue by ppayun** [launchdarkly/python-server-sdk#298]
https://github.com/launchdarkly/python-server-sdk/blob/d152455b89cb70164d8487a1cc0b47f92017a5c4/ldclient/client.py#L471

We use default value for some flags, and this logic keep writing warnings to the logs, can the log level be changed to DEBUG?

        if not context.valid:
            log.warning("Context was invalid for flag evaluation (%s); returning default value" % context.error)
            return EvaluationDetail(default, None, error_reason('USER_NOT_SPECIFIED')), None

**Comment by keelerm84** [comment]
This error should only be shown when the context you are providing is considered invalid. Is there a reason you are trying to use an invalid context?

The reason the context is invalid should be in the logged error.

**Comment by ppayun** [comment]
I just checked, for some reason, the code is using an empty context. We can definitely add some context info. But still why empty context is illegal and showing as warning?

**Comment by keelerm84** [comment]
@ppayun my apologies for the long delay in responding.

Providing a key is a requirement of our context model. We use the provided contexts to populate things like the context drop down list in our UI, and it is also used for aggregating metrics for things like experimentation, etc.

While we do not require many attributes to be set for a context, we do require a key and a valid kind (which will to default to 'user').
