### ISSUE TITLE
Intermittent Flagz `FLAG_NOT_FOUND` Issues in Python Due to Non-Streaming Defaults

### ISSUE THREAD

**Issue by ded-jajmera** [launchdarkly/python-server-sdk#318]
**Describe the bug**
We are observing transient flagz `FLAG_NOT_FOUND` issues in Python.

We think this might be because the cache TTL [is set to 15 seconds by default](https://github.com/launchdarkly/python-server-sdk/blob/8.1.3/ldclient/config.py#L173), which is less than the [default polling interval of 30 seconds](https://github.com/launchdarkly/python-server-sdk/blob/8.1.3/ldclient/feature_store.py#L22-L23). The cache TTL should likely be larger than (~3x) the polling interval.

**To reproduce**
Initialize a flagz client in non-streaming mode with the defaults. Evaluate the feature flag, logging the error reason on any failure.

**Expected behavior**
The flag should be evaluated as normal.

**Logs**
We publish to Sentry with the following logic:
```
def _should_log_error(self, flag_key: str) -> bool:
        self.error_counter[flag_key] += 1
        flag_err_count = self.error_counter[flag_key]
        err_log_prob = 1 / flag_err_count
        return err_log_prob > self.seeded_rand.uniform(0, 1)

(...)

if self._should_log_error(flag_key):
            try:
                with sentry_sdk.push_scope() as scope:
                    scope.set_tag("error_kind", result.reason["errorKind"])
                    scope.set_tag("flag_key", flag_key)
                    scope.set_tag("project_key", self.project_key)
                    scope.set_tag("result_type", str(type(result.value)))
                    sentry_sdk.capture_message(
                        "non-nil error getting launchdarkly flag",
                    )
```
We observed many such Sentry events:

<img width="333" alt="image" src="https://github.com/user-attachments/assets/3d55af27-7d50-452c-b1a7-a674caeee8c3">

**SDK version**
8.1.3.

**Language version, developer tools**
Python 3.8.10. 

**OS/platform**
macOS Sonoma 14.6.1.

**Additional context**
N/A.

**Comment by keelerm84** [comment]
> We think this might be because the cache TTL [is set to 15 seconds by default](https://github.com/launchdarkly/python-server-sdk/blob/8.1.3/ldclient/config.py#L173), which is less than the [default polling interval of 30 seconds](https://github.com/launchdarkly/python-server-sdk/blob/8.1.3/ldclient/feature_store.py#L22-L23). The cache TTL should likely be larger than (~3x) the polling interval.
>
>
> Initialize a flagz client in non-streaming mode with the defaults. Evaluate the feature flag, > logging the error reason on any failure.

The default 15 second cache expiration should not affect the SDK operation if you are using the default configuration. That expiration only comes into play when using a persistence store. 

Are you making use of something like redis, consul, or dynamodb?
