### ISSUE TITLE
ldclient.get() call is getting hanged (time out) on updating requests version to 2.18.4 from 2.12.5

### ISSUE THREAD

**Issue by akash-gautam** [launchdarkly/python-server-sdk#86]
Description: The ldclient.get() call is getting timed out in my service on updating the requests version from 2.12.5 to 2.18.4 . On probing further I found out that the ldclient.get() method calls LDClient (in client.py file) and LDClient calls self._update_processor.start() this is the call which is actually getting timed out. If I comment out the self._update_processor.start() call then the ldclient.get() runs fine.  One more thing is that ldclient has a requirement requests>=2.17.3 but still it seems to be working with the lower version. I tried with the updated versions of ldclient as well but got the same behaviour.

Env details:
Python: 2.7
LDClient: 5.0.4
Requests: 2.18.4
Ubuntu:14.04

**Comment by akash-gautam** [comment]
Thanks for your time Eli. I am using streaming mode(stream=True),  self._update_processor is actually getting timed out, self._update_processor call the run method of StreamingUpdateProcessor class (in streaming.py file), which in turn makes series of calls like _connect followed by SSEClient wherein it calls _connect method where I observe that call to self.resp.iter_content(chunk_size=self._chunk_size, decode_unicode=True) seems to be hanging. When I comment it out this line things works as expected.

Note, that the chunk_size is 10000 and decode_unicode is set as True.

**Comment by eli-darkly** [comment]
Closing this because our SDK doesn't use the `requests` package any more.
